name: mydeployment
env:
  APP_NAME: "template_react"
  #key: 

#on: [push]

on:
  push:
    branches:
      - main
      
jobs: 
  mysendcode:
    runs-on: ubuntu-latest
  
    steps: 
      - name: Print Hello Message
        run : echo "Hello from GitHub stepanpr ${{ env.APP_NAME }}"
        
      - name: SHOW_ALL
        run : ls -la
    
